/**
 * ESPHome Host Platform Simulator Integration
 * 
 * This module enables running LVGL designs in a native simulator window
 * using ESPHome's host platform with SDL display.
 * 
 * Requirements (macOS): brew install sdl2 libsodium
 * Requirements (Linux): apt install libsdl2-dev libsodium-dev
 */

import { Logger } from '../utils/logger.js';
import { AppState } from '../core/state.js';
import { emit, EVENTS } from '../core/events.js';
import { hasHaBackend, HA_API_BASE, getHaToken } from '../utils/env.js';

// Simulator state
let simulatorStatus = 'idle'; // 'idle', 'starting', 'running', 'error'
let simulatorProcess = null;

/**
 * Extract a top-level YAML section by key.
 * Handles multi-line sections properly.
 */
function extractYamlSection(yaml, sectionName) {
    // Match from section start to next top-level key or end of file
    // Top-level keys start at column 0 with no leading whitespace
    const regex = new RegExp(`^${sectionName}:.*(?:\\n(?:[ \\t].*|\\s*$))*`, 'm');
    const match = yaml.match(regex);
    return match ? match[0].trim() : '';
}

/**
 * Modify the LVGL section to use the simulator display and touchscreen.
 * Replaces any display/touchscreen references with simulator_display/simulator_touch.
 */
function modifyLvglForSimulator(lvglSection) {
    if (!lvglSection) return lvglSection;
    
    // Replace display references
    let modified = lvglSection
        // Replace display: xxx with display: simulator_display
        .replace(/display:\s*\w+/g, 'display: simulator_display')
        // Replace touchscreens list items
        .replace(/(-\s*)(\w+_touch\w*)/g, '$1simulator_touch');
    
    // If displays section exists, ensure it references simulator_display
    if (modified.includes('displays:')) {
        modified = modified.replace(
            /displays:\s*\n(\s*-\s*display:\s*)\w+/,
            'displays:\n$1simulator_display'
        );
    }
    
    // If touchscreens section exists under displays, update it
    modified = modified.replace(
        /touchscreens:\s*\n(\s*-\s*)\w+/g,
        'touchscreens:\n$1simulator_touch'
    );
    
    return modified;
}

/**
 * Generate a host-platform compatible YAML configuration for the simulator.
 * This wraps the current LVGL design in a host+SDL configuration.
 */
export function generateSimulatorYaml() {
    const settings = AppState.settings || {};
    const pages = AppState.pages || [];
    const dims = AppState.getCanvasDimensions();
    
    // Get the current LVGL YAML from the snippet box
    const snippetBox = document.getElementById('snippetBox');
    const currentYaml = snippetBox?.value || '';
    
    // Extract relevant sections from the generated YAML
    const lvglSection = extractYamlSection(currentYaml, 'lvgl');
    const sensorSection = extractYamlSection(currentYaml, 'sensor');
    const textSensorSection = extractYamlSection(currentYaml, 'text_sensor');
    const binarySensorSection = extractYamlSection(currentYaml, 'binary_sensor');
    const fontSection = extractYamlSection(currentYaml, 'font');
    
    // Build the simulator YAML
    const yaml = `# ESPHome Host Platform Simulator
# Auto-generated by ESPHome Designer
# Requirements: brew install sdl2 libsodium (macOS)
#              apt install libsdl2-dev libsodium-dev (Linux)

esphome:
  name: lvgl-simulator
  friendly_name: "LVGL Simulator"
  
host:
  # Optional: Set a MAC address for Home Assistant API connection
  # mac_address: "62:23:45:AF:B3:DD"

logger:
  level: DEBUG

# Home Assistant API (optional - for live entity data)
# api:
#   encryption:
#     key: "your-encryption-key"

# SDL Display - renders to a native window
display:
  - platform: sdl
    id: simulator_display
    dimensions:
      width: ${dims.width}
      height: ${dims.height}
    auto_clear_enabled: false
    update_interval: 16ms

# Touch simulation via mouse
touchscreen:
  - platform: sdl
    id: simulator_touch
    display: simulator_display

${fontSection || `# Font definitions (commonly needed)
font:
  - file: "gfonts://Roboto"
    id: roboto_14
    size: 14
  - file: "gfonts://Roboto"
    id: roboto_16
    size: 16
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20
  - file: "gfonts://Roboto"
    id: roboto_24
    size: 24
  - file: "gfonts://Roboto"
    id: roboto_28
    size: 28
  - file: "gfonts://Roboto"
    id: roboto_32
    size: 32
  - file: "gfonts://Montserrat"
    id: montserrat_12
    size: 12
  - file: "gfonts://Montserrat"
    id: montserrat_14
    size: 14
  - file: "gfonts://Montserrat"
    id: montserrat_16
    size: 16
  - file: "gfonts://Montserrat"
    id: montserrat_20
    size: 20
  - file: "gfonts://Montserrat"
    id: montserrat_24
    size: 24
  - file: "gfonts://Montserrat"
    id: montserrat_28
    size: 28`}

${lvglSection ? modifyLvglForSimulator(lvglSection) : `# LVGL Configuration
lvgl:
  displays:
    - display: simulator_display
      touchscreens:
        - simulator_touch
  pages:
    - id: main_page
      widgets:
        - label:
            align: CENTER
            text: "No LVGL content generated yet"
            text_color: 0xFFFFFF`}

${sensorSection}

${textSensorSection}

${binarySensorSection}
`;
    
    return yaml;
}

/**
 * Check if the simulator dependencies are available
 */
export async function checkSimulatorDependencies() {
    if (!hasHaBackend()) {
        return {
            available: false,
            reason: 'Simulator requires Home Assistant backend connection'
        };
    }
    
    try {
        const response = await fetch(`${HA_API_BASE}/simulator/check`, {
            method: 'GET',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${getHaToken()}`
            }
        });
        
        if (response.ok) {
            const data = await response.json();
            return data;
        } else {
            return {
                available: false,
                reason: 'Simulator endpoint not available'
            };
        }
    } catch (err) {
        Logger.warn('[Simulator] Dependency check failed:', err);
        return {
            available: false,
            reason: 'Could not connect to simulator service'
        };
    }
}

/**
 * Start the ESPHome simulator with the current design
 */
export async function startSimulator() {
    if (simulatorStatus === 'running') {
        Logger.warn('[Simulator] Already running');
        return { success: false, error: 'Simulator is already running' };
    }
    
    simulatorStatus = 'starting';
    emit(EVENTS.SIMULATOR_STATUS_CHANGED, { status: 'starting' });
    
    const yaml = generateSimulatorYaml();
    Logger.log('[Simulator] Generated YAML for simulator');
    
    try {
        const response = await fetch(`${HA_API_BASE}/simulator/start`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${getHaToken()}`
            },
            body: JSON.stringify({ yaml })
        });
        
        if (response.ok) {
            const data = await response.json();
            simulatorStatus = 'running';
            simulatorProcess = data.process_id;
            emit(EVENTS.SIMULATOR_STATUS_CHANGED, { status: 'running', process_id: data.process_id });
            Logger.log('[Simulator] Started successfully');
            return { success: true, process_id: data.process_id };
        } else {
            const error = await response.text();
            simulatorStatus = 'error';
            emit(EVENTS.SIMULATOR_STATUS_CHANGED, { status: 'error', error });
            Logger.error('[Simulator] Failed to start:', error);
            return { success: false, error };
        }
    } catch (err) {
        simulatorStatus = 'error';
        emit(EVENTS.SIMULATOR_STATUS_CHANGED, { status: 'error', error: err.message });
        Logger.error('[Simulator] Error starting:', err);
        return { success: false, error: err.message };
    }
}

/**
 * Stop the running simulator
 */
export async function stopSimulator() {
    if (simulatorStatus !== 'running') {
        return { success: true };
    }
    
    try {
        const response = await fetch(`${HA_API_BASE}/simulator/stop`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${getHaToken()}`
            },
            body: JSON.stringify({ process_id: simulatorProcess })
        });
        
        simulatorStatus = 'idle';
        simulatorProcess = null;
        emit(EVENTS.SIMULATOR_STATUS_CHANGED, { status: 'idle' });
        
        if (response.ok) {
            Logger.log('[Simulator] Stopped successfully');
            return { success: true };
        } else {
            const error = await response.text();
            Logger.warn('[Simulator] Stop returned error:', error);
            return { success: true }; // Still consider it stopped
        }
    } catch (err) {
        simulatorStatus = 'idle';
        simulatorProcess = null;
        emit(EVENTS.SIMULATOR_STATUS_CHANGED, { status: 'idle' });
        Logger.warn('[Simulator] Error stopping:', err);
        return { success: true }; // Still consider it stopped
    }
}

/**
 * Get the current simulator status
 */
export function getSimulatorStatus() {
    return {
        status: simulatorStatus,
        process_id: simulatorProcess
    };
}

/**
 * Download the simulator YAML file for manual use
 */
export function downloadSimulatorYaml() {
    const yaml = generateSimulatorYaml();
    const blob = new Blob([yaml], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = 'lvgl-simulator.yaml';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    Logger.log('[Simulator] Downloaded simulator YAML');
}

/**
 * Copy simulator YAML to clipboard
 */
export async function copySimulatorYaml() {
    const yaml = generateSimulatorYaml();
    try {
        await navigator.clipboard.writeText(yaml);
        Logger.log('[Simulator] Copied simulator YAML to clipboard');
        return true;
    } catch (err) {
        Logger.error('[Simulator] Failed to copy to clipboard:', err);
        return false;
    }
}

/**
 * Show instructions for running the simulator manually
 */
export function showSimulatorInstructions() {
    const yaml = generateSimulatorYaml();
    
    const instructions = `
# ESPHome LVGL Simulator Instructions

## Prerequisites

### macOS:
\`\`\`bash
brew install esphome sdl2 libsodium
xcode-select --install  # If not already installed
\`\`\`

### Linux (Debian/Ubuntu):
\`\`\`bash
pip install esphome
sudo apt install libsdl2-dev libsodium-dev build-essential
\`\`\`

## Running the Simulator

1. Save the YAML below to a file (e.g., \`simulator.yaml\`)
2. Run: \`esphome run simulator.yaml\`
3. A window will open showing your LVGL design

## Notes

- The simulator uses SDL2 to render the display in a native window
- Mouse clicks simulate touch input
- Press Ctrl+C in the terminal to stop the simulator
- For Home Assistant connectivity, uncomment the \`api:\` section

---

${yaml}
`;
    
    return instructions;
}

// Register simulator event
if (typeof EVENTS !== 'undefined' && !EVENTS.SIMULATOR_STATUS_CHANGED) {
    EVENTS.SIMULATOR_STATUS_CHANGED = 'simulator:status_changed';
}
